name: CI Package

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
             
            - name: Install pyinstaller
              run: pip3 install pyinstaller

            - name: Create distributable release
              run: | 
                pyinstaller --onefile __main__.py
                mv ./dist/__main__ ./dist/data-entry

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "$('%Y-%m-%d')"
                files: |
                  ./dist/data-entry