name: CI Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
             
            - name: Install black
              run: pip3 install black
            
            - name: Enforce formatting with black
              run: python3 -m black --check .

            - name: Install pylint
              run: pip3 install pylint

            - name: Install all dependencies
              run: pip3 install -r requirements.txt

            - name: Enforce best practices with pylint in tests
              run: python3 -m pylint *.py